{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gradle.serviceAccountName" . }}
  labels:
  {{ include "gradle.labels" . | nindent 4 }}
  {{- end -}}